<a href="https://colab.research.google.com/github/a6ishek/Ipynb_Files_ML-DL/blob/main/Diabetes_predusing_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
import tensorflow.keras as tf

In [ ]:
Data = pd.read_csv("/content/diabetes.csv")
Data

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
Data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
X = Data.iloc[:,:8]
Y = Data.iloc[:,-1]
print(X,Y)
np.shape(X)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[76

(768, 8)

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.15,random_state = 1)

In [ ]:
Y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
def ratio(x,y):#to find x's percent in overall data(x+y)
   return (x/(x+y))*100



In [ ]:
ratio(425,227)

65.1840490797546

In [ ]:
Y_train.value_counts()

0    425
1    227
Name: Outcome, dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values = 0,strategy='mean')
X_train = si.fit_transform(X_train)
X_test = si.fit_transform(X_test)

In [ ]:
model = tf.models.Sequential()
model.add(tf.layers.Dense(64,input_dim=8,activation='relu'))
model.add(tf.layers.Dense(128,activation='relu'))
model.add(tf.layers.Dense(256,activation='relu'))
model.add(tf.layers.Dense(1,activation='sigmoid'))

In [ ]:
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X_train,Y_train,epochs=500)

Epoch 1/500
21/21 [==============================] - 0s 2ms/step - loss: 1.6589 - accuracy: 0.5690
Epoch 2/500
21/21 [==============================] - 0s 2ms/step - loss: 0.7034 - accuracy: 0.6871
Epoch 3/500
21/21 [==============================] - 0s 2ms/step - loss: 0.8487 - accuracy: 0.6074
Epoch 4/500
21/21 [==============================] - 0s 2ms/step - loss: 0.6305 - accuracy: 0.6779
Epoch 5/500
21/21 [==============================] - 0s 2ms/step - loss: 0.5816 - accuracy: 0.7055
Epoch 6/500
21/21 [==============================] - 0s 2ms/step - loss: 0.6425 - accuracy: 0.6503
Epoch 7/500
21/21 [==============================] - 0s 2ms/step - loss: 0.6744 - accuracy: 0.6733
Epoch 8/500
21/21 [==============================] - 0s 2ms/step - loss: 0.5707 - accuracy: 0.7316
Epoch 9/500
21/21 [==============================] - 0s 2ms/step - loss: 0.6478 - accuracy: 0.6887
Epoch 10/500
21/21 [==============================] - 0s 2ms/step - loss: 0.6153 - accuracy: 0.6902
Epoch 11/

In [ ]:
Y_pred = model.predict(X_test)
Y_pred

array([[1.7796451e-01],
       [9.4381142e-01],
       [3.7450373e-02],
       [3.6520771e-22],
       [1.7240644e-03],
       [2.8862241e-01],
       [6.4092207e-01],
       [9.9086952e-01],
       [8.9952528e-01],
       [8.1370443e-02],
       [9.9799597e-01],
       [1.5731635e-08],
       [0.0000000e+00],
       [9.9969953e-01],
       [1.6727448e-03],
       [9.8354393e-01],
       [3.2385623e-01],
       [7.6791781e-07],
       [8.7306695e-14],
       [9.9655402e-01],
       [1.1445880e-03],
       [1.8159086e-01],
       [9.9999976e-01],
       [9.4761759e-02],
       [3.4350172e-08],
       [4.3863547e-01],
       [5.6823790e-03],
       [3.5426068e-01],
       [4.8794985e-02],
       [7.1159184e-01],
       [1.0162622e-02],
       [3.7535489e-02],
       [9.8428972e-09],
       [6.5821779e-01],
       [4.3058813e-02],
       [4.8107207e-03],
       [9.4624905e-11],
       [2.6654303e-03],
       [6.2238174e-17],
       [1.0000000e+00],
       [8.2612038e-04],
       [1.080933

In [ ]:
Y_pred = Y_pred.round()


In [ ]:
Y_pred

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],

In [ ]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[62 13]
 [19 22]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.79        75
           1       0.63      0.54      0.58        41

    accuracy                           0.72       116
   macro avg       0.70      0.68      0.69       116
weighted avg       0.72      0.72      0.72       116



In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                576       
_________________________________________________________________
dense_5 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_6 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 257       
Total params: 42,177
Trainable params: 42,177
Non-trainable params: 0
_________________________________________________________________
